### ISSUE TITLE
Translation placeholder not replaces: lockNHeader

### ISSUE THREAD

**Issue by Techworker** [appditto/blaise_wallet_flutter#1]
https://github.com/appditto/blaise_wallet_flutter/blob/55e6539150623b88759c63573cbbe5344b928cf2/lib/l10n/intl_de.arb#L148-L152

The `%1` values are not replaced when displayed in the security settings.

Version: 0.9.3
Android

**Comment by yekta** [comment]
Thank you. We're already aware and it'll be fixed with the next version that'll arrive shortly.

**Comment by bbedward** [comment]
Fixed in 90e1728441aea6c59bafc0690b0489b07fc6cbd8
