### ISSUE TITLE
Inclusion in F-Droid

### ISSUE THREAD

**Issue by Poussinou** [appditto/blaise_wallet_flutter#2]
Hi,

Since this app is MIT licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you?

**Comment by bbedward** [comment]
We would be open to including it on f-droid, we would just want somebody reputable from the PascalCoin community to be responsible for the listing.

**Comment by Poussinou** [comment]
Let's start with a [Request For Packaging](https://gitlab.com/fdroid/rfp/issues) if it's ok for you. We will then add a recipe to build this app on our side. This can be done by one of your guy or by a F-Droid packager. Anyway, everything is clearly public and freely accessible by everyone.

**Comment by Poussinou** [comment]
`com.google.gms.google-services` is not a FLOSS library, does the app still works without it, and is it possible to write a build flavor without proprietary stuff in it for F-Droid?
